// supabase/functions/_shared/exerciseImage.ts
// The one exercise image generator. Prompt from the row (name, equipment,
// description, discipline), picture from Gemini, stored in the
// exercise-images bucket. Imported by generate-exercise-image (the legacy
// entry point) and enrich-exercise. Nothing here writes the exercises row —
// the caller decides what to record alongside the URL.
// Spec: docs/superpowers/specs/2026-09-11-catalog-enrichment-pipeline-design.md §5
import type { SupabaseClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { decode as decodeBase64 } from 'https://deno.land/std@0.168.0/encoding/base64.ts';

export const IMAGE_BUCKET = 'exercise-images';
const GEMINI_ENDPOINT =
  'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent';

/** The row columns the prompt reads. */
export interface ImageRow {
  id: string;
  name: string;
  description: string | null;
  core_default_equipment: string | null;
  exercise_equipment: { equipment: { name: string } | null }[] | null;
}

export const IMAGE_ROW_SELECT = 'id, name, description, core_default_equipment, exercise_equipment(equipment(name))';

/** Junction names first, else the core's default list, else bodyweight. */
export function equipmentListOf(row: ImageRow): string {
  const junction = (row.exercise_equipment ?? [])
    .map((ee) => ee.equipment?.name)
    .filter((n): n is string => typeof n === 'string' && n !== '');
  const core = (row.core_default_equipment ?? '').split(',').map((s) => s.trim()).filter(Boolean);
  return (junction.length > 0 ? junction : core).join(', ') || 'bodyweight';
}

export function buildImagePrompt(row: ImageRow, discipline: string | null): string {
  const person = discipline ? `an athletic ${discipline} athlete` : 'an athletic person';
  const gym = discipline ? `Modern ${discipline} gym environment` : 'Modern gym environment';
  return `Professional fitness photography of ${person} demonstrating the "${row.name}" exercise.

Requirements:
- Photorealistic image, high quality sports photography style
- Fit, athletic model with proper form and technique
- ${gym} with professional lighting
- Equipment: ${equipmentListOf(row)}
- Dynamic pose showing the exercise movement
- Dramatic lighting, cinematic quality
- No text, watermarks, or labels
- Focus on muscle engagement and proper form
${row.description ? `- Movement: ${row.description}` : ''}

Style: Realistic fitness photography like Nike or Under Armour advertising campaigns.`;
}

export class ImageGenerationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'ImageGenerationError';
  }
}

/** One Gemini call. Throws ImageGenerationError on any failure. */
export async function generateImageBytes(
  geminiApiKey: string, prompt: string,
): Promise<{ bytes: Uint8Array; mimeType: string }> {
  const res = await fetch(GEMINI_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-goog-api-key': geminiApiKey },
    body: JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: { response_modalities: ['IMAGE'], image_config: { aspect_ratio: '16:9' } },
    }),
  });
  if (!res.ok) {
    const detail = await res.text();
    throw new ImageGenerationError(`Gemini API error: ${res.status} ${detail.slice(0, 300)}`);
  }
  const data = await res.json();
  const candidates = Array.isArray(data?.candidates) ? data.candidates : [];
  if (candidates.length === 0) throw new ImageGenerationError('No images generated by Gemini');
  const parts = (candidates[0]?.content?.parts ?? []) as Record<string, unknown>[];
  const part = parts.find((p) => p.inlineData || p.inline_data);
  if (!part) throw new ImageGenerationError('No inline image data in Gemini response');
  const inline = (part.inlineData ?? part.inline_data) as { data?: string; mimeType?: string; mime_type?: string };
  if (typeof inline.data !== 'string') throw new ImageGenerationError('No inline image data found');
  return {
    bytes: decodeBase64(inline.data),
    mimeType: inline.mimeType || inline.mime_type || 'image/png',
  };
}

/** Upload to the exercise-images bucket; returns the public URL. */
export async function storeImage(
  supabase: SupabaseClient, exerciseId: string, bytes: Uint8Array, mimeType: string,
): Promise<string> {
  const fileName = `exercises/${exerciseId}_${Date.now()}.png`;
  const { error } = await supabase.storage.from(IMAGE_BUCKET).upload(fileName, bytes, {
    contentType: mimeType, upsert: true,
  });
  if (error) throw new ImageGenerationError(`Failed to upload image: ${error.message}`);
  return supabase.storage.from(IMAGE_BUCKET).getPublicUrl(fileName).data.publicUrl;
}

/**
 * Read the row, build the prompt, generate, store. Returns the public URL.
 * Does NOT update exercises.image_url — callers write it with whatever
 * provenance they own. Throws ImageGenerationError (or a plain Error when
 * the row is missing).
 */
export async function generateAndStoreImage(
  supabase: SupabaseClient, exerciseId: string, opts: { geminiApiKey: string; discipline: string | null },
): Promise<string> {
  const { data, error } = await supabase.from('exercises').select(IMAGE_ROW_SELECT).eq('id', exerciseId).single();
  if (error) throw new Error(`exercise read failed: ${error.message}`);
  if (!data) throw new Error('Exercise not found');
  const row = data as unknown as ImageRow;
  console.log(`Generating image for exercise: ${row.name}`);
  const prompt = buildImagePrompt(row, opts.discipline);
  const { bytes, mimeType } = await generateImageBytes(opts.geminiApiKey, prompt);
  const url = await storeImage(supabase, exerciseId, bytes, mimeType);
  console.log(`Image generated for exercise ${row.name}: ${url}`);
  return url;
}
