import { StyleSheet } from "react-native";
import { colors } from "@/src/lib/colors";

export const nutritionStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
  },
  headerTitle: { color: colors.foreground, fontSize: 20, fontWeight: "700" },
  headerAction: { color: colors.primary, fontSize: 16, fontWeight: "600" },
  card: {
    backgroundColor: colors.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: "700",
    marginBottom: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
  },
  rowLabel: { color: colors.foreground, fontSize: 15, flexShrink: 1 },
  rowValue: { color: colors.mutedForeground, fontSize: 15 },
  banner: {
    backgroundColor: "rgba(34,197,94,0.12)",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primary,
    padding: 12,
    marginTop: 12,
  },
  bannerText: { color: colors.foreground, fontSize: 14, marginBottom: 8 },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
  },
  primaryButtonText: {
    color: colors.primaryForeground,
    fontSize: 15,
    fontWeight: "700",
  },
  mutedText: { color: colors.mutedForeground, fontSize: 13 },
  mutedTextSpaced: { marginTop: 12 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 4 },
  chip: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { color: colors.mutedForeground, fontSize: 13 },
  chipTextActive: { color: colors.primaryForeground, fontWeight: "700" },
  input: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    color: colors.foreground,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 15,
  },
  destructiveButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.destructive,
    paddingVertical: 10,
    alignItems: "center",
    marginTop: 12,
  },
  destructiveButtonText: { color: "#F87171", fontSize: 15, fontWeight: "600" },
  chipPickerContainer: { paddingVertical: 10 },
  flexShrinkColumn: { flexShrink: 1 },
});
