// deno-lint-ignore-file no-explicit-any
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface MovementImageRequest {
  movementId: string;
  prompt: string;
  userId: string;
}

// Helper function to upload image and update movement
async function uploadAndUpdateMovement(
  supabaseUrl: string,
  supabaseServiceKey: string,
  userId: string,
  movementId: string,
  imageBuffer: Uint8Array,
  contentType: string
): Promise<string> {
  const supabase = createClient(supabaseUrl, supabaseServiceKey);

  const fileName = `${userId}/${movementId}_${Date.now()}.${contentType === 'image/svg+xml' ? 'svg' : 'png'}`;
  const { data: uploadData, error: uploadError } = await supabase.storage
    .from('movement-images')
    .upload(fileName, imageBuffer, {
      contentType,
      upsert: false,
    });

  if (uploadError) {
    console.error('Upload error:', uploadError);
    throw new Error(`Failed to upload image: ${uploadError.message}`);
  }

  console.log('Image uploaded successfully:', uploadData.path);

  // Get public URL
  const { data: { publicUrl } } = supabase.storage
    .from('movement-images')
    .getPublicUrl(uploadData.path);

  // Update exercise record with image URL
  const { error: updateError } = await supabase
    .from('exercises')
    .update({
      image_url: publicUrl,
    })
    .eq('id', movementId);

  if (updateError) {
    console.error('Database update error:', updateError);
    // Don't throw - image is uploaded successfully
  }

  return publicUrl;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    // Get Gemini API key from environment
    const geminiApiKey = Deno.env.get('GEMINI_API_KEY');
    if (!geminiApiKey) {
      console.error('GEMINI_API_KEY not configured - skipping image generation');
      return new Response(
        JSON.stringify({ success: false, error: 'API key not configured' }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get Supabase credentials
    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error('Supabase credentials not configured');
    }

    // Parse request body
    const { movementId, prompt, userId }: MovementImageRequest = await req.json();

    if (!movementId || !prompt || !userId) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: movementId, prompt, userId' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`Generating image for movement ${movementId}...`);
    console.log('Prompt:', prompt);

    // Use Gemini 2.5 Flash Image API for image generation
    const geminiEndpoint = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent';

    const geminiResponse = await fetch(geminiEndpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-goog-api-key': geminiApiKey,
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          response_modalities: ['IMAGE'],
          image_config: {
            aspect_ratio: '16:9',  // Widescreen for movement detail pages
          }
        }
      }),
    });

    if (!geminiResponse.ok) {
      const errorText = await geminiResponse.text();
      console.error('Gemini API error:', geminiResponse.status, errorText);

      return new Response(
        JSON.stringify({
          success: false,
          error: `Gemini API error: ${geminiResponse.status}`,
          message: 'Image generation failed'
        }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const geminiData = await geminiResponse.json();
    console.log('Gemini response:', JSON.stringify(geminiData, null, 2));

    // Extract image data from Gemini response
    if (!geminiData.candidates || geminiData.candidates.length === 0) {
      throw new Error('No images generated by Gemini');
    }

    const imagePart = geminiData.candidates[0]?.content?.parts?.find(
      (part: any) => part.inlineData || part.inline_data
    );

    if (!imagePart) {
      throw new Error('No inline image data in Gemini response');
    }

    // Support both camelCase (inlineData) and snake_case (inline_data)
    const inlineData = imagePart.inlineData || imagePart.inline_data;
    if (!inlineData) {
      throw new Error('No inline image data found');
    }

    const imageBase64 = inlineData.data;
    const mimeType = inlineData.mimeType || inlineData.mime_type || 'image/png';

    console.log('Image mime type:', mimeType);
    const imageBuffer = Uint8Array.from(atob(imageBase64), c => c.charCodeAt(0));

    // Upload to Supabase Storage and update movement
    const publicUrl = await uploadAndUpdateMovement(
      supabaseUrl,
      supabaseServiceKey,
      userId,
      movementId,
      imageBuffer,
      mimeType
    );

    console.log(`Image generation complete for movement ${movementId}`);

    return new Response(
      JSON.stringify({
        success: true,
        imageUrl: publicUrl,
        movementId,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in generate-movement-image function:', error);

    return new Response(
      JSON.stringify({
        error: error.message || 'Failed to generate image',
        success: false,
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
