// deno-lint-ignore-file no-explicit-any
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface ExerciseImageRequest {
  exerciseId: string;
  userId: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    // Get API keys from environment
    const geminiApiKey = Deno.env.get('GEMINI_API_KEY');
    if (!geminiApiKey) {
      console.error('GEMINI_API_KEY not configured');
      return new Response(
        JSON.stringify({ success: false, error: 'API key not configured' }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL');
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
    if (!supabaseUrl || !supabaseServiceKey) {
      throw new Error('Supabase credentials not configured');
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Parse request
    const { exerciseId, userId }: ExerciseImageRequest = await req.json();

    if (!exerciseId || !userId) {
      return new Response(
        JSON.stringify({ error: 'Missing required fields: exerciseId, userId' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Fetch exercise details
    const { data: exercise, error: exerciseError } = await supabase
      .from('exercises')
      .select('id, name, description, equipment_types')
      .eq('id', exerciseId)
      .single();

    if (exerciseError || !exercise) {
      return new Response(
        JSON.stringify({ error: 'Exercise not found' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log(`Generating image for exercise: ${exercise.name}`);

    // Build prompt for image generation - realistic style matching WOD images
    const equipmentList = exercise.equipment_types?.join(', ') || 'bodyweight';
    const prompt = `Professional fitness photography of an athletic person demonstrating the "${exercise.name}" exercise.

Requirements:
- Photorealistic image, high quality sports photography style
- Fit, athletic model with proper form and technique
- Modern gym environment with professional lighting
- Equipment: ${equipmentList}
- Dynamic pose showing the exercise movement
- Dramatic lighting, cinematic quality
- No text, watermarks, or labels
- Focus on muscle engagement and proper form
${exercise.description ? `- Movement: ${exercise.description}` : ''}

Style: Realistic fitness photography like Nike or Under Armour advertising campaigns.`;

    // Call Gemini 2.5 Flash Image API
    const geminiEndpoint = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent';

    const geminiResponse = await fetch(geminiEndpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-goog-api-key': geminiApiKey,
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }]
        }],
        generationConfig: {
          response_modalities: ['IMAGE'],
          image_config: {
            aspect_ratio: '16:9',  // Wide hero/banner format
          }
        }
      }),
    });

    if (!geminiResponse.ok) {
      const errorText = await geminiResponse.text();
      console.error('Gemini API error:', geminiResponse.status, errorText);
      return new Response(
        JSON.stringify({ success: false, error: `Gemini API error: ${geminiResponse.status}` }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const geminiData = await geminiResponse.json();
    console.log('Gemini response received');

    // Extract image data
    if (!geminiData.candidates || geminiData.candidates.length === 0) {
      throw new Error('No images generated by Gemini');
    }

    const imagePart = geminiData.candidates[0]?.content?.parts?.find(
      (part: any) => part.inlineData || part.inline_data
    );

    if (!imagePart) {
      throw new Error('No inline image data in Gemini response');
    }

    const inlineData = imagePart.inlineData || imagePart.inline_data;
    const imageBase64 = inlineData.data;
    const mimeType = inlineData.mimeType || inlineData.mime_type || 'image/png';

    // Convert base64 to Uint8Array
    const imageBuffer = Uint8Array.from(atob(imageBase64), c => c.charCodeAt(0));

    // Upload to Supabase Storage
    const fileName = `exercises/${exerciseId}_${Date.now()}.png`;
    const { data: uploadData, error: uploadError } = await supabase.storage
      .from('exercise-images')
      .upload(fileName, imageBuffer, {
        contentType: mimeType,
        upsert: true,
      });

    if (uploadError) {
      console.error('Upload error:', uploadError);
      throw new Error(`Failed to upload image: ${uploadError.message}`);
    }

    // Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from('exercise-images')
      .getPublicUrl(fileName);

    // Update exercise record
    const { error: updateError } = await supabase
      .from('exercises')
      .update({ image_url: publicUrl })
      .eq('id', exerciseId);

    if (updateError) {
      console.error('Database update error:', updateError);
    }

    console.log(`Image generated for exercise ${exercise.name}: ${publicUrl}`);

    return new Response(
      JSON.stringify({
        success: true,
        imageUrl: publicUrl,
        exerciseId,
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in generate-exercise-image function:', error);
    return new Response(
      JSON.stringify({
        error: error.message || 'Failed to generate image',
        success: false,
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
