// The "Eat Next" recommender (Nutrition OS Phase 3). Pure, deterministic,
// no I/O — same input, same output, always. Reasons are generated by the
// same predicates that rank, so the UI can never claim a reason the ranking
// didn't use. Spec: docs/superpowers/specs/2026-07-29-nutrition-recommender-design.md §5.
//
// Policy constants are code, not schema (rampProgress/mealScore stance).
import type { MealPaceState } from "./mealPace";
import type { BrianScoreResult } from "./mealScore";
import type { MacroGoals, MacroTotals } from "./mealMacros";
import type { MealTotals, MealWithItems, MealRole } from "@/src/types/meal-library";

export const POST_WORKOUT_WINDOW_MIN = 180;
export const EMERGENCY_MIN_GAP_CAL = 400;
export const CATCH_UP_BAND = 0.35;
export const NUDGE_MIN_GAP_CAL = 250;
export const NUDGE_MILESTONE_OFFSET_MIN = 20;
export const EMERGENCY_CHECK_BEFORE_END_MIN = 90;
export const PROTEIN_SHORT_G = 15;
export const PROTEIN_SHORT_MAX_CAL = 300;
export const POST_WORKOUT_MIN_PROTEIN_G = 25;
export const BRIDGE_PREFER_GAP_MIN = 120;
export const PREP_HARD_CAP_FACTOR = 2;
const TOP_N = 3;

export type EatNextContext =
  | "after_window"
  | "goal_hit"
  | "post_workout"
  | "emergency"
  | "catch_up"
  | "next_meal";

export interface ScoredMeal {
  meal: MealWithItems;
  totals: MealTotals;
  score: BrianScoreResult;
}

export interface EatNextInput {
  nowMinutes: number;
  windowStartMinutes: number;
  windowEndMinutes: number;
  mealTimesMinutes: { breakfast: number; lunch: number; dinner: number };
  dayTotals: MacroTotals;
  goals: MacroGoals;
  caloriePace: MealPaceState;
  proteinPace: MealPaceState;
  meals: ScoredMeal[];
  maxPrepMinutes: number;
  workoutCompletedAtMinutes: number | null;
  nudgesEnabled: boolean;
}

export interface EatNextRecommendation {
  mealId: string;
  name: string;
  reasons: string[];
}

export interface EatNextNudge {
  fireAtMinutes: number;
  title: string;
  body: string;
}

export interface EatNextResult {
  context: EatNextContext;
  message: string | null;
  recommendations: EatNextRecommendation[];
  nudge: EatNextNudge | null;
}

interface Candidate extends ScoredMeal {
  extraReasons: string[];
  roleRank: number; // 0 = preferred role, 1 = otherwise (lower sorts first)
}

function baseEligible(m: ScoredMeal, maxPrepMinutes: number): boolean {
  if (m.score.containsNever) return false;
  return m.meal.prep_minutes <= maxPrepMinutes * PREP_HARD_CAP_FACTOR;
}

function prepReason(m: ScoredMeal, maxPrepMinutes: number): string[] {
  return m.meal.prep_minutes > maxPrepMinutes
    ? [`${m.meal.prep_minutes} min — over your prep budget`]
    : [];
}

function rank(cands: Candidate[]): Candidate[] {
  return [...cands].sort(
    (a, b) =>
      a.roleRank - b.roleRank ||
      // Rank on the un-renormalized component sum: Phase 2's banding analysis
      // found the rounded /100 score barely discriminates (all seeds 84-95);
      // raw is strictly finer and ties less. UI still DISPLAYS score/100.
      b.score.raw - a.score.raw ||
      a.meal.prep_minutes - b.meal.prep_minutes ||
      a.meal.name.localeCompare(b.meal.name),
  );
}

function toRecs(cands: Candidate[], contextReason: (c: Candidate) => string[]): EatNextRecommendation[] {
  return cands.slice(0, TOP_N).map((c) => ({
    mealId: c.meal.id,
    name: c.meal.name,
    reasons: [...contextReason(c), ...c.extraReasons],
  }));
}

function candidate(
  m: ScoredMeal,
  preferredRoles: ReadonlyArray<MealRole>,
  maxPrepMinutes: number,
): Candidate {
  return {
    ...m,
    extraReasons: prepReason(m, maxPrepMinutes),
    roleRank: m.meal.role !== null && preferredRoles.includes(m.meal.role) ? 0 : 1,
  };
}

/** Next main-meal slot strictly after now, else snack (mealPace's milestone rule). */
function nextSlot(
  nowMinutes: number,
  mealTimesMinutes: EatNextInput["mealTimesMinutes"],
): { slot: "breakfast" | "lunch" | "dinner" | "snack"; atMinutes: number | null } {
  const entries = [
    { slot: "breakfast" as const, atMinutes: mealTimesMinutes.breakfast },
    { slot: "lunch" as const, atMinutes: mealTimesMinutes.lunch },
    { slot: "dinner" as const, atMinutes: mealTimesMinutes.dinner },
  ]
    .filter((e) => e.atMinutes > nowMinutes)
    .sort((a, b) => a.atMinutes - b.atMinutes);
  return entries[0] ?? { slot: "snack", atMinutes: null };
}

export function recommendEatNext(input: EatNextInput): EatNextResult {
  const {
    nowMinutes, windowEndMinutes, mealTimesMinutes, dayTotals, goals,
    caloriePace, meals, maxPrepMinutes, workoutCompletedAtMinutes,
  } = input;

  const eligible = meals.filter((m) => baseEligible(m, maxPrepMinutes));
  const nudge = computeNudge(input);

  // 1. after_window — terminal.
  if (nowMinutes > windowEndMinutes) {
    return { context: "after_window", message: "Eating window closed for today.", recommendations: [], nudge: null };
  }

  // 2. goal_hit — terminal (protein-short exception recommends within it).
  const calorieGoal = goals.calories;
  if (calorieGoal != null && calorieGoal > 0 && dayTotals.calories >= calorieGoal) {
    const proteinGoal = goals.protein;
    const proteinShort =
      proteinGoal != null && proteinGoal - dayTotals.protein >= PROTEIN_SHORT_G;
    if (proteinShort) {
      const q = eligible
        .filter(
          (m) =>
            (m.meal.role === "bridge" || m.meal.role === "calorie_booster") &&
            m.totals.calories < PROTEIN_SHORT_MAX_CAL,
        )
        .sort(
          (a, b) =>
            b.totals.protein - a.totals.protein ||
            a.meal.name.localeCompare(b.meal.name),
        );
      if (q.length > 0) {
        const top = q[0];
        const gap = Math.round((proteinGoal ?? 0) - dayTotals.protein);
        return {
          context: "goal_hit",
          message: "Calorie target hit — protein still short.",
          recommendations: [{
            mealId: top.meal.id,
            name: top.meal.name,
            reasons: [
              `protein short by ~${gap} g`,
              `${Math.round(top.totals.protein)} g protein in ${Math.round(top.totals.calories)} cal`,
              ...prepReason(top, maxPrepMinutes),
            ],
          }],
          nudge: null,
        };
      }
    }
    return { context: "goal_hit", message: "Target hit — nothing needed.", recommendations: [], nudge: null };
  }

  // 3. post_workout — falls through when empty.
  if (
    workoutCompletedAtMinutes !== null &&
    nowMinutes - workoutCompletedAtMinutes >= 0 &&
    nowMinutes - workoutCompletedAtMinutes <= POST_WORKOUT_WINDOW_MIN
  ) {
    const cands = eligible
      .filter(
        (m) =>
          m.meal.role === "post_workout" ||
          m.totals.protein >= POST_WORKOUT_MIN_PROTEIN_G,
      )
      .map((m) => candidate(m, ["post_workout"], maxPrepMinutes));
    if (cands.length > 0) {
      return {
        context: "post_workout",
        message: null,
        recommendations: toRecs(rank(cands), (c) => [
          c.meal.role === "post_workout"
            ? "post-workout meal"
            : `post-workout — ${Math.round(c.totals.protein)} g protein`,
        ]),
        nudge,
      };
    }
  }

  const behind = caloriePace.status === "behind";
  const gap = behind ? caloriePace.catchUpAmount ?? 0 : 0;

  // 4. emergency — falls through when empty.
  if (behind && nowMinutes > mealTimesMinutes.dinner && gap >= EMERGENCY_MIN_GAP_CAL) {
    const cands = eligible
      .filter(
        (m) =>
          m.meal.category === "emergency" ||
          m.meal.role === "emergency_catchup" ||
          m.meal.role === "calorie_booster",
      )
      .map((m) => candidate(m, ["emergency_catchup", "calorie_booster"], maxPrepMinutes))
      // Emergency ranks by rescue size, not score (spec §5.3.4).
      .sort(
        (a, b) =>
          b.totals.calories - a.totals.calories ||
          a.meal.name.localeCompare(b.meal.name),
      );
    if (cands.length > 0) {
      return {
        context: "emergency",
        message: `~${gap} cal to go before day's end`,
        recommendations: toRecs(cands, (c) => [
          `~${gap} cal to go — ${Math.round(c.totals.calories)} cal, ${c.meal.prep_minutes} min prep`,
        ]),
        nudge,
      };
    }
  }

  // 5. catch_up — falls through when empty.
  if (behind && gap > 0) {
    const cands = eligible
      .filter((m) => Math.abs(m.totals.calories - gap) <= gap * CATCH_UP_BAND)
      .map((m) => candidate(m, ["bridge"], maxPrepMinutes));
    if (cands.length > 0) {
      return {
        context: "catch_up",
        message: `${gap} cal behind pace`,
        recommendations: toRecs(rank(cands), (c) => [
          `closes the ~${gap} cal gap (${Math.round(c.totals.calories)} cal, ${c.meal.prep_minutes} min)`,
        ]),
        nudge,
      };
    }
  }

  // 6. next_meal — default.
  const { slot, atMinutes } = nextSlot(nowMinutes, mealTimesMinutes);
  const slotCategories: ReadonlyArray<string> =
    slot === "snack" ? ["snack", "shake"] : [slot];
  const farFromMeal =
    atMinutes !== null && atMinutes - nowMinutes >= BRIDGE_PREFER_GAP_MIN;
  const preferredRoles: ReadonlyArray<MealRole> = farFromMeal ? ["bridge"] : [];
  const pool = farFromMeal
    ? eligible.filter(
        (m) =>
          slotCategories.includes(m.meal.category) ||
          m.meal.role === "bridge" ||
          m.meal.category === "snack",
      )
    : eligible.filter((m) => slotCategories.includes(m.meal.category));
  const cands = pool.map((m) => candidate(m, preferredRoles, maxPrepMinutes));
  return {
    context: "next_meal",
    message:
      cands.length === 0
        ? meals.length === 0
          ? "No meals in your library yet."
          : `Nothing in the library fits ${slot} right now.`
        : null,
    recommendations: toRecs(rank(cands), () => [
      slot === "snack" ? "between meals" : `next: ${slot}`,
    ]),
    nudge,
  };
}

// Task 2 replaces this stub with the real decision (spec §5.6).
function computeNudge(_input: EatNextInput): EatNextNudge | null {
  return null;
}
