// The "Eat Next" recommender (Nutrition OS Phase 3). Pure, deterministic,
// no I/O — same input, same output, always. Reasons are generated by the
// same predicates that rank, so the UI can never claim a reason the ranking
// didn't use. Spec: docs/superpowers/specs/2026-07-29-nutrition-recommender-design.md §5.
//
// Policy constants are code, not schema (rampProgress/mealScore stance).
import type { MealPaceState } from "./mealPace";
import type { BrianScoreResult } from "./mealScore";
import type { MacroGoals, MacroTotals } from "./mealMacros";
import {
  assessAssemblability,
  type AssemblabilityInventoryRow,
} from "./stockState";
import type { MealCategory, MealTotals, MealWithItems, MealRole } from "@/src/types/meal-library";

export const POST_WORKOUT_WINDOW_MIN = 180;
export const EMERGENCY_MIN_GAP_CAL = 400;
export const CATCH_UP_BAND = 0.35;
export const NUDGE_MIN_GAP_CAL = 250;
export const NUDGE_MILESTONE_OFFSET_MIN = 20;
export const EMERGENCY_CHECK_BEFORE_END_MIN = 90;
export const PROTEIN_SHORT_G = 15;
export const PROTEIN_SHORT_MAX_CAL = 300;
export const POST_WORKOUT_MIN_PROTEIN_G = 25;
export const BRIDGE_PREFER_GAP_MIN = 120;
export const PREP_HARD_CAP_FACTOR = 2;
/** Task 8's `EatNextHomeCard` derives its empty-library CTA from this exact
 * string (see plan Task 8) — exported so that comparison is against one
 * source, not a copy-pasted literal that a wording edit could silently break. */
export const EMPTY_LIBRARY_MESSAGE = "No meals in your library yet.";
const TOP_N = 3;

export type EatNextContext =
  | "after_window"
  | "goal_hit"
  | "post_workout"
  | "emergency"
  | "catch_up"
  | "next_meal";

export interface ScoredMeal {
  meal: MealWithItems;
  totals: MealTotals;
  score: BrianScoreResult;
}

export interface EatNextInput {
  nowMinutes: number;
  // Carried for spec §5.1 fidelity but not read by this task (nor by Task 2's
  // planned nudge code): `windowStartMinutes` has no context that starts
  // before the window (before_window already falls through to next_meal via
  // caloriePace.status), and the protein-short check below reads raw
  // `goals`/`dayTotals` instead of `proteinPace` because `MealPaceState.status`
  // can't express "≥15 g short" — only ahead/behind/on_pace/goal_hit.
  windowStartMinutes: number;
  windowEndMinutes: number;
  mealTimesMinutes: { breakfast: number; lunch: number; dinner: number };
  dayTotals: MacroTotals;
  goals: MacroGoals;
  caloriePace: MealPaceState;
  proteinPace: MealPaceState;
  meals: ScoredMeal[];
  maxPrepMinutes: number;
  workoutCompletedAtMinutes: number | null;
  nudgesEnabled: boolean;
  stockByMealId?: Map<string, EatNextStockInfo>;
}

export interface EatNextStockInfo {
  assemblable: boolean;
  missingCount: number;
  expiringItemName: string | null;
  expiringDaysLeft: number | null;
}

/** The `meals` shape `buildStockByMealId` reads: a structural subset of
 *  `MealWithItems` (assignable with no cast), narrowed to the four fields
 *  `assessAssemblability` actually consumes so this module doesn't take on
 *  the whole meal-library surface — and so a test fixture is three fields,
 *  not a full `Meal` plus a full `SavedFood`. */
export interface StockAssessmentMeal {
  id: string;
  items: Array<{
    saved_food_id: string;
    savedFood: { name: string; barcode: string | null };
  }>;
}

/**
 * Builds the optional `stockByMealId` above out of what `fetchMealLibrary`
 * already returns.
 *
 * **Lives here, next to its only reader** (`candidate()`'s
 * `stockByMealId?.get(m.meal.id)`, further down this file), so both halves of the
 * lookup-key seam sit in one file and are pinned by one test file. That seam
 * is silent when broken: Task 9 round 2 showed a wrong key on the read side
 * degenerates ranking to Phase 3 — no stock reasons, no availability-aware
 * nudge — with 81/81 tests still green. The write side has the same property.
 * The plan (Task 10 Step 1) inlined this block in `useEatNext.ts`; that file
 * is a React hook and this repo's Jest run covers pure libs only, so inlining
 * would have left both the key AND the decision below unpinnable. Recorded in
 * "⚠️ Execution amendments → Task 10".
 *
 * **DECISION (Task 10) — an ITEM-LESS meal is OMITTED from the map**, so it
 * ranks `stockRank: 1` (unknown) and carries no stock reason at all, instead
 * of the `stockRank: 2` + `"missing 0 ingredients"` that `assessAssemblability`
 * would otherwise yield (`assemblable = items.length > 0 && missing.length === 0`,
 * `stockState.ts`). Item-less meals are live state, not hypothetical:
 * `updateMeal` deletes then re-inserts items non-atomically and says so in its
 * own comment (`mealLibrary.ts:310-313`). The argument:
 *   - Rank 2 asserts "we established you can't make this". For a meal with no
 *     recorded ingredients we established nothing — `missing` is empty because
 *     there was nothing to check, not because nothing is missing. That is a
 *     positive claim with no evidence behind it, and it mislabels the tier for
 *     every other member of it.
 *   - Rank 0 is the opposite over-claim: it would say "in stock" about a meal
 *     we cannot verify and promote a corrupt record ABOVE meals we positively
 *     confirmed the user can assemble. Strictly the worst option.
 *   - Rank 1 is the literal epistemic state, and it is exactly what this map's
 *     existing "no entry = unknown" semantics already mean — so it needs no new
 *     field and creates no second way to be unknown.
 * Omitting also drops the reason string for free rather than special-casing a
 * formatter, which keeps this in step with Task 8's `MealDetail` fix (gate on
 * the missing LIST, not on the `assemblable` verdict) instead of inventing a
 * third rendering of the same state. The user-visible effect is that a broken
 * meal surfaces plainly, with nothing claimed about its stock — and surfacing
 * is the recovery path, since `updateMeal`'s comment notes item-less meals are
 * "recoverable by re-editing".
 *
 * **Input contract.** Everything here is trusted, not validated — this is a
 * pure function with one production caller — so the expectations are stated
 * instead:
 * @param library.meals every meal to rank. Item-less ones are skipped (above).
 * @param library.conceptIdsBySavedFoodId must be COMPLETE. A miss defaults to
 *   `[]`, which silently makes that item resolvable by barcode only, so it
 *   counts as missing and the meal reads unassemblable. Under-claiming is the
 *   intended failure direction, but a partial map produces wrong answers with
 *   no error.
 * @param library.inventory the WHOLE inventory, not pre-filtered per meal:
 *   `assessAssemblability` indexes it by id to find the most urgent expiring
 *   row across everything the meal resolved to.
 * A `meals`/`inventory` inconsistency is absorbed as "missing", never thrown.
 *
 * **Why `MealLibraryModal` computes its own `assemblabilityById` instead of
 * sharing this** (the one home for this argument — the call site in
 * `useEatNext.ts` and the modal both point here rather than restating it).
 * They run the same predicate over the same inputs but are not the same value:
 * the modal holds `MealAssemblability` because it renders the missing item
 * NAMES and filters `inStockOnly` on the verdict, while this holds the
 * four-field `EatNextStockInfo` for a comparator. Their lifetimes differ more
 * than their shapes — the modal's is a `useMemo` keyed on that modal's own
 * `data`, alive while a sheet is open; this is a per-fetch local in a hook
 * whose consumers include the background nudge scheduler and which refetches
 * on focus and after every meal write. Sharing would couple two independent
 * fetch lifetimes behind a cache whose staleness bugs would be silent, to save
 * arithmetic that is already free: ~50 meals x ~10 items x ~25 inventory rows
 * is sub-millisecond and dwarfed by the round trip that produced its inputs.
 * `MealBuilder` holds a third copy for a third reason (a draft meal with no
 * row yet). Duplicate computation, single DEFINITION — all three call
 * `assessAssemblability`.
 */
export function buildStockByMealId(library: {
  meals: StockAssessmentMeal[];
  conceptIdsBySavedFoodId: Map<string, string[]>;
  inventory: AssemblabilityInventoryRow[];
}): Map<string, EatNextStockInfo> {
  const map = new Map<string, EatNextStockInfo>();
  for (const meal of library.meals) {
    if (meal.items.length === 0) continue; // see DECISION above
    const a = assessAssemblability({
      items: meal.items.map((it) => ({
        savedFoodId: it.saved_food_id,
        name: it.savedFood.name,
        barcode: it.savedFood.barcode,
        conceptIds: library.conceptIdsBySavedFoodId.get(it.saved_food_id) ?? [],
      })),
      inventory: library.inventory,
    });
    // Keyed by `meal.id`, which MUST stay in lockstep with `candidate()`'s
    // `.get(m.meal.id)`. Pinned from both sides in eatNext.test.ts.
    map.set(meal.id, {
      assemblable: a.assemblable,
      missingCount: a.missing.length,
      expiringItemName: a.expiringItemName,
      expiringDaysLeft: a.expiringDaysLeft,
    });
  }
  return map;
}

export interface EatNextRecommendation {
  mealId: string;
  name: string;
  reasons: string[];
  /** Rounded to match how the reason strings already render these numbers
   *  (`Math.round`), so the structured fields and any reason text that
   *  happens to embed the same number can never disagree on screen. */
  calories: number;
  protein: number;
  prepMinutes: number;
  /** The /100 renormalized score (`BrianScoreResult.score`), NOT `raw`.
   *  Spec §5.5: ranking reads `raw`; "UI surfaces still display `score`/100."
   *  This field is the UI-facing one — do not swap it for `raw`. */
  score: number;
}

export interface EatNextNudge {
  /** Minutes since local midnight, on the SAME local day as the `nowMinutes`
   *  that produced it. Always `> nowMinutes` and `<= windowEndMinutes`.
   *  Consumers must resolve it against that same day, not a fresh `new Date()`. */
  fireAtMinutes: number;
  title: string;
  body: string;
}

function sameLocalDay(a: Date, b: Date): boolean {
  return (
    a.getFullYear() === b.getFullYear() &&
    a.getMonth() === b.getMonth() &&
    a.getDate() === b.getDate()
  );
}

/**
 * Resolves `EatNextNudge.fireAtMinutes` (see the doc comment just above:
 * minutes since local midnight on the SAME local day as the `nowMinutes`
 * that produced it — "consumers must resolve it against that same day, not
 * a fresh `new Date()`") to a concrete instant, honoring that contract by
 * construction: `sourceDay` is a required argument, not an assumption a
 * caller can skip. Co-located with the interface it resolves so the two
 * cannot drift apart the way a caller-side reimplementation could.
 *
 * Returns `null` in either of two cases, both meaning "do not schedule
 * this decision":
 *  - `sourceDay` and `now` fall on different local calendar days — the
 *    decision is stale (e.g. computed just before local midnight, resolved
 *    just after; see the eatNudgeService.ts amendment this was extracted
 *    to fix).
 *  - The resolved instant is not strictly after `now` — already passed.
 *
 * Pure: takes `now` rather than reading the clock, so the engine stays free
 * of I/O and tests control time directly. The `new Date(...)` below is
 * deterministic construction from its arguments, not a clock read — this is
 * the one place `new Date(` appears in this otherwise-clockless file; note
 * for anyone grepping for purity regressions. It's also freshly constructed,
 * not a mutation of `sourceDay` (no `.setHours(...)` on the caller's Date) —
 * `sourceDay` may be the exact object a caller is holding in state (see
 * `useEatNext.ts`'s `computedAt`), and mutating it in place would corrupt
 * that state as a side effect of what looks like a pure read.
 */
export function nudgeFireDate(
  fireAtMinutes: number,
  sourceDay: Date,
  now: Date,
): Date | null {
  if (!sameLocalDay(sourceDay, now)) return null;
  // `Math.floor` on the hour is redundant with the `Date` constructor's own
  // truncation of a fractional hour component (verified, including across a
  // DST-transition day) — kept anyway so this reads as an intentional
  // hour/minute split, not a value left for the constructor to fix up.
  const fireDate = new Date(
    sourceDay.getFullYear(),
    sourceDay.getMonth(),
    sourceDay.getDate(),
    Math.floor(fireAtMinutes / 60),
    fireAtMinutes % 60,
    0,
    0,
  );
  if (fireDate.getTime() <= now.getTime()) return null;
  return fireDate;
}

export interface EatNextResult {
  context: EatNextContext;
  message: string | null;
  recommendations: EatNextRecommendation[];
  nudge: EatNextNudge | null;
}

interface Candidate extends ScoredMeal {
  extraReasons: string[];
  roleRank: number; // 0 = preferred role, 1 = otherwise (lower sorts first)
  // 0 = assemblable now, 1 = unknown (no map, or no entry for this meal),
  // 2 = known-missing. Three-way, not boolean: "we don't know" must not be
  // treated as "we know it's missing" — an unknown meal still outranks one
  // we've positively established the user can't make.
  stockRank: number;
  // 0 = uses an expiring in-stock item (a rescue), 1 = otherwise.
  expiringRank: number;
}

/** Spec §9's stock reason strings. Availability is never a hard filter —
 *  an unmakeable meal still surfaces, it just ranks last and says why. */
function stockReasons(info: EatNextStockInfo | undefined): string[] {
  if (!info) return [];
  const out = info.assemblable
    ? ["in stock"]
    : [`missing ${info.missingCount} ingredient${info.missingCount === 1 ? "" : "s"}`];
  // The expiring line is appended on BOTH branches — deliberately, adopting
  // Task 8's DECISION for the same signal in MealDetail: the rescue is about
  // an ingredient the user ALREADY OWNS, which is *more* actionable when the
  // meal is unmakeable, not less ("buying the two missing items also saves
  // the one about to spoil"). Suppressing it here would also rank on a signal
  // the UI never states — `expiringRank` is deliberately NOT conditioned on
  // `assemblable`, and the two must agree.
  // `expiringItemName != null`, NOT truthiness on `expiringDaysLeft`:
  // `expiringDaysLeft: 0` means "expires today", the MOST urgent value
  // `assessAssemblability` can return (its window is bounded below at 0 so
  // already-expired rows never reach here) — and `0` is falsy. See the Task 2
  // execution amendment's forward note.
  if (info.expiringItemName != null) {
    // Day 0 gets its own string rather than "expires in 0d", matching the
    // treatment Task 8 shipped in MealDetail for the same value: the most
    // urgent day would otherwise read as the least urgent-sounding copy.
    out.push(
      info.expiringDaysLeft === 0
        ? `uses ${info.expiringItemName} — expires today`
        : `uses ${info.expiringItemName} — expires in ${info.expiringDaysLeft}d`,
    );
  }
  return out;
}

function baseEligible(m: ScoredMeal, maxPrepMinutes: number): boolean {
  if (m.score.containsNever) return false;
  return m.meal.prep_minutes <= maxPrepMinutes * PREP_HARD_CAP_FACTOR;
}

function prepReason(m: ScoredMeal, maxPrepMinutes: number): string[] {
  return m.meal.prep_minutes > maxPrepMinutes
    ? [`${m.meal.prep_minutes} min — over your prep budget`]
    : [];
}

function rank(cands: Candidate[]): Candidate[] {
  return [...cands].sort(
    (a, b) =>
      a.roleRank - b.roleRank ||
      // Availability sits between role and score (spec §9): the context's
      // role preference still wins — a post-workout meal you must shop for
      // beats a plain one in the fridge — but below that, "can I make it"
      // outranks "how good is it", and rescuing an expiring item breaks
      // ties among the meals you can make.
      a.stockRank - b.stockRank ||
      a.expiringRank - b.expiringRank ||
      // Rank on the un-renormalized component sum: Phase 2's banding analysis
      // found the rounded /100 score barely discriminates (all seeds 84-95);
      // raw is strictly finer and ties less. UI still DISPLAYS score/100.
      b.score.raw - a.score.raw ||
      a.meal.prep_minutes - b.meal.prep_minutes ||
      a.meal.name.localeCompare(b.meal.name),
  );
}

function toRecs(cands: Candidate[], contextReason: (c: Candidate) => string[]): EatNextRecommendation[] {
  return cands.slice(0, TOP_N).map((c) => ({
    mealId: c.meal.id,
    name: c.meal.name,
    reasons: [...contextReason(c), ...c.extraReasons],
    calories: Math.round(c.totals.calories),
    protein: Math.round(c.totals.protein),
    prepMinutes: c.meal.prep_minutes,
    score: c.score.score,
  }));
}

function candidate(
  m: ScoredMeal,
  preferredRoles: ReadonlyArray<MealRole>,
  maxPrepMinutes: number,
  preferredCategories: ReadonlyArray<MealCategory> = [],
  stockByMealId?: Map<string, EatNextStockInfo>,
): Candidate {
  const roleMatch = m.meal.role !== null && preferredRoles.includes(m.meal.role);
  const categoryMatch = preferredCategories.includes(m.meal.category);
  const info = stockByMealId?.get(m.meal.id);
  return {
    ...m,
    extraReasons: [...prepReason(m, maxPrepMinutes), ...stockReasons(info)],
    roleRank: roleMatch || categoryMatch ? 0 : 1,
    // No map, or no entry for this meal → 1 (unknown), which sorts after
    // in-stock and before known-missing. An absent map therefore leaves
    // every candidate tied on both new terms, i.e. bit-for-bit prior order.
    stockRank: info === undefined ? 1 : info.assemblable ? 0 : 2,
    expiringRank: info !== undefined && info.expiringItemName != null ? 0 : 1,
  };
}

/** Calorie half of the goal_hit rule (spec §5.3.2): calories at/over goal,
 * with a null/zero goal never counting as "hit" (mirrors `computeMealPace`'s
 * `goal == null || goal <= 0` treatment in mealPace.ts). Extracted so Task 2's
 * planned nudge code — which the plan text re-derives this same expression
 * for — has one predicate to call instead of a second copy to drift from. */
function calorieGoalHit(goals: MacroGoals, dayTotals: MacroTotals): boolean {
  const calorieGoal = goals.calories;
  return calorieGoal != null && calorieGoal > 0 && dayTotals.calories >= calorieGoal;
}

/** Spec §5.3.5's catch-up candidate set: eligible meals within ±CATCH_UP_BAND
 *  of the gap, `bridge` preferred. Shared by the catch_up context and the
 *  nudge's own body pick so the band rule has exactly one definition. */
function catchUpCandidates(
  eligible: ScoredMeal[], gap: number, maxPrepMinutes: number,
  stockByMealId?: Map<string, EatNextStockInfo>,
): Candidate[] {
  return eligible
    .filter((m) => Math.abs(m.totals.calories - gap) <= gap * CATCH_UP_BAND)
    .map((m) => candidate(m, ["bridge"], maxPrepMinutes, [], stockByMealId));
}

/** Next main-meal slot strictly after now, else snack (mealPace's milestone rule). */
function nextSlot(
  nowMinutes: number,
  mealTimesMinutes: EatNextInput["mealTimesMinutes"],
): { slot: "breakfast" | "lunch" | "dinner" | "snack"; atMinutes: number | null } {
  const entries = [
    { slot: "breakfast" as const, atMinutes: mealTimesMinutes.breakfast },
    { slot: "lunch" as const, atMinutes: mealTimesMinutes.lunch },
    { slot: "dinner" as const, atMinutes: mealTimesMinutes.dinner },
  ]
    .filter((e) => e.atMinutes > nowMinutes)
    .sort((a, b) => a.atMinutes - b.atMinutes);
  return entries[0] ?? { slot: "snack", atMinutes: null };
}

export function recommendEatNext(input: EatNextInput): EatNextResult {
  const {
    nowMinutes, windowEndMinutes, mealTimesMinutes, dayTotals, goals,
    caloriePace, meals, maxPrepMinutes, workoutCompletedAtMinutes, stockByMealId,
  } = input;

  const eligible = meals.filter((m) => baseEligible(m, maxPrepMinutes));
  const nudge = computeNudge(input);

  // 1. after_window — terminal.
  if (nowMinutes > windowEndMinutes) {
    return { context: "after_window", message: "Eating window closed for today.", recommendations: [], nudge: null };
  }

  // 2. goal_hit — terminal (protein-short exception recommends within it).
  if (calorieGoalHit(goals, dayTotals)) {
    const proteinGoal = goals.protein;
    const proteinGap = proteinGoal != null ? proteinGoal - dayTotals.protein : 0;
    const proteinShort = proteinGoal != null && proteinGap >= PROTEIN_SHORT_G;
    if (proteinShort) {
      const q = eligible
        .filter(
          (m) =>
            (m.meal.role === "bridge" || m.meal.role === "calorie_booster") &&
            m.totals.calories < PROTEIN_SHORT_MAX_CAL,
        )
        .sort(
          (a, b) =>
            b.totals.protein - a.totals.protein ||
            a.meal.name.localeCompare(b.meal.name),
        );
      if (q.length > 0) {
        const top = q[0];
        return {
          context: "goal_hit",
          message: "Calorie target hit — protein still short.",
          recommendations: [{
            mealId: top.meal.id,
            name: top.meal.name,
            reasons: [
              `protein short by ~${Math.round(proteinGap)} g`,
              `${Math.round(top.totals.protein)} g protein in ${Math.round(top.totals.calories)} cal`,
              ...prepReason(top, maxPrepMinutes),
            ],
            calories: Math.round(top.totals.calories),
            protein: Math.round(top.totals.protein),
            prepMinutes: top.meal.prep_minutes,
            score: top.score.score,
          }],
          nudge: null,
        };
      }
    }
    return { context: "goal_hit", message: "Target hit — nothing needed.", recommendations: [], nudge: null };
  }

  // 3. post_workout — falls through when empty.
  if (
    workoutCompletedAtMinutes !== null &&
    nowMinutes - workoutCompletedAtMinutes >= 0 &&
    nowMinutes - workoutCompletedAtMinutes <= POST_WORKOUT_WINDOW_MIN
  ) {
    const cands = eligible
      .filter(
        (m) =>
          m.meal.role === "post_workout" ||
          m.totals.protein >= POST_WORKOUT_MIN_PROTEIN_G,
      )
      .map((m) => candidate(m, ["post_workout"], maxPrepMinutes, [], stockByMealId));
    if (cands.length > 0) {
      return {
        context: "post_workout",
        message: null,
        recommendations: toRecs(rank(cands), (c) => [
          c.meal.role === "post_workout"
            ? "post-workout meal"
            : `post-workout — ${Math.round(c.totals.protein)} g protein`,
        ]),
        nudge,
      };
    }
  }

  const behind = caloriePace.status === "behind";
  const gap = behind ? caloriePace.catchUpAmount ?? 0 : 0;

  // 4. emergency — falls through when empty.
  if (behind && nowMinutes > mealTimesMinutes.dinner && gap >= EMERGENCY_MIN_GAP_CAL) {
    const cands = eligible
      .filter(
        (m) =>
          m.meal.category === "emergency" ||
          m.meal.role === "emergency_catchup" ||
          m.meal.role === "calorie_booster",
      )
      // `candidate()` is called only for its `extraReasons` (prep-budget and
      // stock copy) here — the `roleRank`/`stockRank`/`expiringRank` it
      // computes are deliberately unread by the calories-descending sort
      // below (spec §5.3.4: rescue size, not role, score or availability,
      // decides emergency order — a bigger rescue you must shop for still
      // beats a small one in the fridge). The map is still forwarded so the
      // reasons say what's makeable. Do not "fix" this by routing it
      // through `rank()`.
      .map((m) => candidate(m, ["emergency_catchup", "calorie_booster"], maxPrepMinutes, [], stockByMealId))
      // Emergency ranks by rescue size, not score (spec §5.3.4).
      .sort(
        (a, b) =>
          b.totals.calories - a.totals.calories ||
          a.meal.name.localeCompare(b.meal.name),
      );
    if (cands.length > 0) {
      return {
        context: "emergency",
        message: `~${gap} cal to go before day's end`,
        recommendations: toRecs(cands, (c) => [
          `~${gap} cal to go — ${Math.round(c.totals.calories)} cal, ${c.meal.prep_minutes} min prep`,
        ]),
        nudge,
      };
    }
  }

  // 5. catch_up — falls through when empty.
  if (behind && gap > 0) {
    const cands = catchUpCandidates(eligible, gap, maxPrepMinutes, stockByMealId);
    if (cands.length > 0) {
      return {
        context: "catch_up",
        message: `${gap} cal behind pace`,
        recommendations: toRecs(rank(cands), (c) => [
          `closes the ~${gap} cal gap (${Math.round(c.totals.calories)} cal, ${c.meal.prep_minutes} min)`,
        ]),
        nudge,
      };
    }
  }

  // 6. next_meal — default.
  const { slot, atMinutes } = nextSlot(nowMinutes, mealTimesMinutes);
  const slotCategories: ReadonlyArray<MealCategory> =
    slot === "snack" ? ["snack", "shake"] : [slot];
  const farFromMeal =
    atMinutes !== null && atMinutes - nowMinutes >= BRIDGE_PREFER_GAP_MIN;
  const preferredRoles: ReadonlyArray<MealRole> = farFromMeal ? ["bridge"] : [];
  const preferredCategories: ReadonlyArray<MealCategory> = farFromMeal ? ["snack"] : [];
  const pool = farFromMeal
    ? eligible.filter(
        (m) =>
          m.meal.category !== "emergency" &&
          (slotCategories.includes(m.meal.category) ||
            m.meal.role === "bridge" ||
            m.meal.category === "snack"),
      )
    : eligible.filter((m) => slotCategories.includes(m.meal.category));
  const cands = pool.map((m) =>
    candidate(m, preferredRoles, maxPrepMinutes, preferredCategories, stockByMealId));
  return {
    context: "next_meal",
    message:
      cands.length === 0
        ? meals.length === 0
          ? EMPTY_LIBRARY_MESSAGE
          : `Nothing in the library fits ${slot} right now.`
        : null,
    recommendations: toRecs(rank(cands), () => [
      slot === "snack" ? "between meals" : `next: ${slot}`,
    ]),
    nudge,
  };
}

/**
 * Spec §5.6. Deliberately independent of the context chain above: this fires
 * later (next milestone + 20 min), while the app is closed, as a static
 * message about closing a calorie gap — so it re-derives its own catch-up-band
 * pick from the gap rather than reading `recommendations[0]`, which reflects
 * whatever context is current *now* (e.g. a small `next_meal` bridge snack
 * would not close a 650 cal gap). Spec §5.6's "the top recommendation" is read
 * as "the top recommendation for closing the gap" for this reason. It still
 * applies the same eligibility (`baseEligible`) and ranking (`rank`) rules as
 * every other context, so it can never suggest a meal the engine considers
 * ineligible — just possibly a different eligible meal than `recommendations[0]`.
 * When nothing lands in the ±`CATCH_UP_BAND` window, it falls back to the
 * single best-ranked eligible meal of any size — a concrete suggestion, even
 * an oversized one, beats a bare "~N cal to go" with nothing to act on. That
 * fallback drops the `bridge` role preference (`[]`, not `["bridge"]`) on
 * purpose: once nothing fits the catch-up profile, "closest to the gap" no
 * longer means anything, so the pick reduces to the plain rank ordering
 * (raw, then prep, then name) rather than pretending a role preference
 * still applies to an out-of-band set.
 */
function computeNudge(input: EatNextInput): EatNextNudge | null {
  const {
    nowMinutes, windowEndMinutes, mealTimesMinutes, dayTotals, goals,
    caloriePace, meals, maxPrepMinutes, nudgesEnabled, stockByMealId,
  } = input;
  if (!nudgesEnabled) return null;
  // Defensive invariants, both unreachable-in-effect through the current call
  // path: `recommendEatNext` already discards this return's `nudge` field
  // whenever `goal_hit`/`after_window` is the resolved context (it hardcodes
  // `nudge: null` there), and the `fireAt > windowEndMinutes` clamp below
  // already forces null whenever `nowMinutes >= windowEndMinutes` (the
  // post-bump `fireAt > nowMinutes` invariant makes the two guards redundant
  // by construction). Kept so `computeNudge` is correct standalone, e.g. if a
  // future refactor calls it outside the context chain. See the Task 2
  // execution amendment (round 1, item 4, and the Correction A finding) for
  // the mutation-tested proof neither guard is currently test-observable.
  if (nowMinutes > windowEndMinutes) return null;
  if (calorieGoalHit(goals, dayTotals)) return null;
  if (caloriePace.status !== "behind") return null;
  // `?? 0`, unlike the two guards above, IS load-bearing: `catchUpAmount` is
  // optional on `MealPaceState` (a `behind` pace can omit it), and without
  // the fallback `undefined < NUDGE_MIN_GAP_CAL` evaluates to `false` — the
  // guard below would silently pass and emit a nudge reading "~undefined cal
  // to go". Reading a missing amount as "nothing owed" is the correct and
  // intentional behavior, not an incidental default.
  const gap = caloriePace.catchUpAmount ?? 0;
  if (gap < NUDGE_MIN_GAP_CAL) return null;

  const { atMinutes } = nextSlot(nowMinutes, mealTimesMinutes);
  let fireAt =
    atMinutes !== null
      ? atMinutes + NUDGE_MILESTONE_OFFSET_MIN
      : windowEndMinutes - EMERGENCY_CHECK_BEFORE_END_MIN;
  if (fireAt <= nowMinutes) fireAt = nowMinutes + NUDGE_MILESTONE_OFFSET_MIN;
  if (fireAt > windowEndMinutes) return null;

  // Best catch-up candidate for the body: same eligibility + ranking rules.
  // (`maxPrepMinutes` reaches catchUpCandidates only to build the "over your
  // prep budget" reason, which the nudge body discards — the nudge honors the
  // same prep budget as the surfaces, it just doesn't restate it.)
  const eligible = meals.filter((m) => baseEligible(m, maxPrepMinutes));
  const inBand = rank(catchUpCandidates(eligible, gap, maxPrepMinutes, stockByMealId));
  const pick =
    inBand[0] ??
    rank(eligible.map((m) => candidate(m, [], maxPrepMinutes, [], stockByMealId)))[0];
  const suggestion = pick
    ? ` — ${pick.meal.name} ${pick.meal.prep_minutes > 0 ? `fixes it in ${pick.meal.prep_minutes} min` : "is ready now"}`
    : "";
  return {
    fireAtMinutes: fireAt,
    title: "Eat something",
    body: `~${gap} cal to go${suggestion}`,
  };
}
