// The "Eat Next" recommender (Nutrition OS Phase 3). Pure, deterministic,
// no I/O — same input, same output, always. Reasons are generated by the
// same predicates that rank, so the UI can never claim a reason the ranking
// didn't use. Spec: docs/superpowers/specs/2026-07-29-nutrition-recommender-design.md §5.
//
// Policy constants are code, not schema (rampProgress/mealScore stance).
import type { MealPaceState } from "./mealPace";
import type { BrianScoreResult } from "./mealScore";
import type { MacroGoals, MacroTotals } from "./mealMacros";
import type { MealCategory, MealTotals, MealWithItems, MealRole } from "@/src/types/meal-library";

export const POST_WORKOUT_WINDOW_MIN = 180;
export const EMERGENCY_MIN_GAP_CAL = 400;
export const CATCH_UP_BAND = 0.35;
export const NUDGE_MIN_GAP_CAL = 250;
export const NUDGE_MILESTONE_OFFSET_MIN = 20;
export const EMERGENCY_CHECK_BEFORE_END_MIN = 90;
export const PROTEIN_SHORT_G = 15;
export const PROTEIN_SHORT_MAX_CAL = 300;
export const POST_WORKOUT_MIN_PROTEIN_G = 25;
export const BRIDGE_PREFER_GAP_MIN = 120;
export const PREP_HARD_CAP_FACTOR = 2;
/** Task 8's `EatNextHomeCard` derives its empty-library CTA from this exact
 * string (see plan Task 8) — exported so that comparison is against one
 * source, not a copy-pasted literal that a wording edit could silently break. */
export const EMPTY_LIBRARY_MESSAGE = "No meals in your library yet.";
const TOP_N = 3;

export type EatNextContext =
  | "after_window"
  | "goal_hit"
  | "post_workout"
  | "emergency"
  | "catch_up"
  | "next_meal";

export interface ScoredMeal {
  meal: MealWithItems;
  totals: MealTotals;
  score: BrianScoreResult;
}

export interface EatNextInput {
  nowMinutes: number;
  // Carried for spec §5.1 fidelity but not read by this task (nor by Task 2's
  // planned nudge code): `windowStartMinutes` has no context that starts
  // before the window (before_window already falls through to next_meal via
  // caloriePace.status), and the protein-short check below reads raw
  // `goals`/`dayTotals` instead of `proteinPace` because `MealPaceState.status`
  // can't express "≥15 g short" — only ahead/behind/on_pace/goal_hit.
  windowStartMinutes: number;
  windowEndMinutes: number;
  mealTimesMinutes: { breakfast: number; lunch: number; dinner: number };
  dayTotals: MacroTotals;
  goals: MacroGoals;
  caloriePace: MealPaceState;
  proteinPace: MealPaceState;
  meals: ScoredMeal[];
  maxPrepMinutes: number;
  workoutCompletedAtMinutes: number | null;
  nudgesEnabled: boolean;
}

export interface EatNextRecommendation {
  mealId: string;
  name: string;
  reasons: string[];
}

export interface EatNextNudge {
  fireAtMinutes: number;
  title: string;
  body: string;
}

export interface EatNextResult {
  context: EatNextContext;
  message: string | null;
  recommendations: EatNextRecommendation[];
  nudge: EatNextNudge | null;
}

interface Candidate extends ScoredMeal {
  extraReasons: string[];
  roleRank: number; // 0 = preferred role, 1 = otherwise (lower sorts first)
}

function baseEligible(m: ScoredMeal, maxPrepMinutes: number): boolean {
  if (m.score.containsNever) return false;
  return m.meal.prep_minutes <= maxPrepMinutes * PREP_HARD_CAP_FACTOR;
}

function prepReason(m: ScoredMeal, maxPrepMinutes: number): string[] {
  return m.meal.prep_minutes > maxPrepMinutes
    ? [`${m.meal.prep_minutes} min — over your prep budget`]
    : [];
}

function rank(cands: Candidate[]): Candidate[] {
  return [...cands].sort(
    (a, b) =>
      a.roleRank - b.roleRank ||
      // Rank on the un-renormalized component sum: Phase 2's banding analysis
      // found the rounded /100 score barely discriminates (all seeds 84-95);
      // raw is strictly finer and ties less. UI still DISPLAYS score/100.
      b.score.raw - a.score.raw ||
      a.meal.prep_minutes - b.meal.prep_minutes ||
      a.meal.name.localeCompare(b.meal.name),
  );
}

function toRecs(cands: Candidate[], contextReason: (c: Candidate) => string[]): EatNextRecommendation[] {
  return cands.slice(0, TOP_N).map((c) => ({
    mealId: c.meal.id,
    name: c.meal.name,
    reasons: [...contextReason(c), ...c.extraReasons],
  }));
}

function candidate(
  m: ScoredMeal,
  preferredRoles: ReadonlyArray<MealRole>,
  maxPrepMinutes: number,
  preferredCategories: ReadonlyArray<MealCategory> = [],
): Candidate {
  const roleMatch = m.meal.role !== null && preferredRoles.includes(m.meal.role);
  const categoryMatch = preferredCategories.includes(m.meal.category);
  return {
    ...m,
    extraReasons: prepReason(m, maxPrepMinutes),
    roleRank: roleMatch || categoryMatch ? 0 : 1,
  };
}

/** Calorie half of the goal_hit rule (spec §5.3.2): calories at/over goal,
 * with a null/zero goal never counting as "hit" (mirrors `computeMealPace`'s
 * `goal == null || goal <= 0` treatment in mealPace.ts). Extracted so Task 2's
 * planned nudge code — which the plan text re-derives this same expression
 * for — has one predicate to call instead of a second copy to drift from. */
function calorieGoalHit(goals: MacroGoals, dayTotals: MacroTotals): boolean {
  const calorieGoal = goals.calories;
  return calorieGoal != null && calorieGoal > 0 && dayTotals.calories >= calorieGoal;
}

/** Next main-meal slot strictly after now, else snack (mealPace's milestone rule). */
function nextSlot(
  nowMinutes: number,
  mealTimesMinutes: EatNextInput["mealTimesMinutes"],
): { slot: "breakfast" | "lunch" | "dinner" | "snack"; atMinutes: number | null } {
  const entries = [
    { slot: "breakfast" as const, atMinutes: mealTimesMinutes.breakfast },
    { slot: "lunch" as const, atMinutes: mealTimesMinutes.lunch },
    { slot: "dinner" as const, atMinutes: mealTimesMinutes.dinner },
  ]
    .filter((e) => e.atMinutes > nowMinutes)
    .sort((a, b) => a.atMinutes - b.atMinutes);
  return entries[0] ?? { slot: "snack", atMinutes: null };
}

export function recommendEatNext(input: EatNextInput): EatNextResult {
  const {
    nowMinutes, windowEndMinutes, mealTimesMinutes, dayTotals, goals,
    caloriePace, meals, maxPrepMinutes, workoutCompletedAtMinutes,
  } = input;

  const eligible = meals.filter((m) => baseEligible(m, maxPrepMinutes));
  const nudge = computeNudge(input);

  // 1. after_window — terminal.
  if (nowMinutes > windowEndMinutes) {
    return { context: "after_window", message: "Eating window closed for today.", recommendations: [], nudge: null };
  }

  // 2. goal_hit — terminal (protein-short exception recommends within it).
  if (calorieGoalHit(goals, dayTotals)) {
    const proteinGoal = goals.protein;
    const proteinGap = proteinGoal != null ? proteinGoal - dayTotals.protein : 0;
    const proteinShort = proteinGoal != null && proteinGap >= PROTEIN_SHORT_G;
    if (proteinShort) {
      const q = eligible
        .filter(
          (m) =>
            (m.meal.role === "bridge" || m.meal.role === "calorie_booster") &&
            m.totals.calories < PROTEIN_SHORT_MAX_CAL,
        )
        .sort(
          (a, b) =>
            b.totals.protein - a.totals.protein ||
            a.meal.name.localeCompare(b.meal.name),
        );
      if (q.length > 0) {
        const top = q[0];
        return {
          context: "goal_hit",
          message: "Calorie target hit — protein still short.",
          recommendations: [{
            mealId: top.meal.id,
            name: top.meal.name,
            reasons: [
              `protein short by ~${Math.round(proteinGap)} g`,
              `${Math.round(top.totals.protein)} g protein in ${Math.round(top.totals.calories)} cal`,
              ...prepReason(top, maxPrepMinutes),
            ],
          }],
          nudge: null,
        };
      }
    }
    return { context: "goal_hit", message: "Target hit — nothing needed.", recommendations: [], nudge: null };
  }

  // 3. post_workout — falls through when empty.
  if (
    workoutCompletedAtMinutes !== null &&
    nowMinutes - workoutCompletedAtMinutes >= 0 &&
    nowMinutes - workoutCompletedAtMinutes <= POST_WORKOUT_WINDOW_MIN
  ) {
    const cands = eligible
      .filter(
        (m) =>
          m.meal.role === "post_workout" ||
          m.totals.protein >= POST_WORKOUT_MIN_PROTEIN_G,
      )
      .map((m) => candidate(m, ["post_workout"], maxPrepMinutes));
    if (cands.length > 0) {
      return {
        context: "post_workout",
        message: null,
        recommendations: toRecs(rank(cands), (c) => [
          c.meal.role === "post_workout"
            ? "post-workout meal"
            : `post-workout — ${Math.round(c.totals.protein)} g protein`,
        ]),
        nudge,
      };
    }
  }

  const behind = caloriePace.status === "behind";
  const gap = behind ? caloriePace.catchUpAmount ?? 0 : 0;

  // 4. emergency — falls through when empty.
  if (behind && nowMinutes > mealTimesMinutes.dinner && gap >= EMERGENCY_MIN_GAP_CAL) {
    const cands = eligible
      .filter(
        (m) =>
          m.meal.category === "emergency" ||
          m.meal.role === "emergency_catchup" ||
          m.meal.role === "calorie_booster",
      )
      // `candidate()` is called only for its `extraReasons` (prep-budget
      // copy) here — the `roleRank` it computes is deliberately unread by
      // the calories-descending sort below (spec §5.3.4: rescue size, not
      // role or score, decides emergency order). Do not "fix" this by
      // routing it through `rank()`.
      .map((m) => candidate(m, ["emergency_catchup", "calorie_booster"], maxPrepMinutes))
      // Emergency ranks by rescue size, not score (spec §5.3.4).
      .sort(
        (a, b) =>
          b.totals.calories - a.totals.calories ||
          a.meal.name.localeCompare(b.meal.name),
      );
    if (cands.length > 0) {
      return {
        context: "emergency",
        message: `~${gap} cal to go before day's end`,
        recommendations: toRecs(cands, (c) => [
          `~${gap} cal to go — ${Math.round(c.totals.calories)} cal, ${c.meal.prep_minutes} min prep`,
        ]),
        nudge,
      };
    }
  }

  // 5. catch_up — falls through when empty.
  if (behind && gap > 0) {
    const cands = eligible
      .filter((m) => Math.abs(m.totals.calories - gap) <= gap * CATCH_UP_BAND)
      .map((m) => candidate(m, ["bridge"], maxPrepMinutes));
    if (cands.length > 0) {
      return {
        context: "catch_up",
        message: `${gap} cal behind pace`,
        recommendations: toRecs(rank(cands), (c) => [
          `closes the ~${gap} cal gap (${Math.round(c.totals.calories)} cal, ${c.meal.prep_minutes} min)`,
        ]),
        nudge,
      };
    }
  }

  // 6. next_meal — default.
  const { slot, atMinutes } = nextSlot(nowMinutes, mealTimesMinutes);
  const slotCategories: ReadonlyArray<MealCategory> =
    slot === "snack" ? ["snack", "shake"] : [slot];
  const farFromMeal =
    atMinutes !== null && atMinutes - nowMinutes >= BRIDGE_PREFER_GAP_MIN;
  const preferredRoles: ReadonlyArray<MealRole> = farFromMeal ? ["bridge"] : [];
  const preferredCategories: ReadonlyArray<MealCategory> = farFromMeal ? ["snack"] : [];
  const pool = farFromMeal
    ? eligible.filter(
        (m) =>
          m.meal.category !== "emergency" &&
          (slotCategories.includes(m.meal.category) ||
            m.meal.role === "bridge" ||
            m.meal.category === "snack"),
      )
    : eligible.filter((m) => slotCategories.includes(m.meal.category));
  const cands = pool.map((m) => candidate(m, preferredRoles, maxPrepMinutes, preferredCategories));
  return {
    context: "next_meal",
    message:
      cands.length === 0
        ? meals.length === 0
          ? EMPTY_LIBRARY_MESSAGE
          : `Nothing in the library fits ${slot} right now.`
        : null,
    recommendations: toRecs(rank(cands), () => [
      slot === "snack" ? "between meals" : `next: ${slot}`,
    ]),
    nudge,
  };
}

/**
 * Spec §5.6. Deliberately independent of the context chain above: this fires
 * later (next milestone + 20 min), while the app is closed, as a static
 * message about closing a calorie gap — so it re-derives its own catch-up-band
 * pick from the gap rather than reading `recommendations[0]`, which reflects
 * whatever context is current *now* (e.g. a small `next_meal` bridge snack
 * would not close a 650 cal gap). Spec §5.6's "the top recommendation" is read
 * as "the top recommendation for closing the gap" for this reason. It still
 * applies the same eligibility (`baseEligible`) and ranking (`rank`) rules as
 * every other context, so it can never suggest a meal the engine considers
 * ineligible — just possibly a different eligible meal than `recommendations[0]`.
 * When nothing lands in the ±`CATCH_UP_BAND` window, it falls back to the
 * single best-ranked eligible meal of any size — a concrete suggestion, even
 * an oversized one, beats a bare "~N cal to go" with nothing to act on.
 */
function computeNudge(input: EatNextInput): EatNextNudge | null {
  const {
    nowMinutes, windowEndMinutes, mealTimesMinutes, dayTotals, goals,
    caloriePace, meals, maxPrepMinutes, nudgesEnabled,
  } = input;
  if (!nudgesEnabled) return null;
  if (nowMinutes > windowEndMinutes) return null;
  if (calorieGoalHit(goals, dayTotals)) return null;
  if (caloriePace.status !== "behind") return null;
  const gap = caloriePace.catchUpAmount ?? 0;
  if (gap < NUDGE_MIN_GAP_CAL) return null;

  const { atMinutes } = nextSlot(nowMinutes, mealTimesMinutes);
  let fireAt =
    atMinutes !== null
      ? atMinutes + NUDGE_MILESTONE_OFFSET_MIN
      : windowEndMinutes - EMERGENCY_CHECK_BEFORE_END_MIN;
  if (fireAt <= nowMinutes) fireAt = nowMinutes + NUDGE_MILESTONE_OFFSET_MIN;
  if (fireAt > windowEndMinutes) return null;

  // Best catch-up candidate for the body: same eligibility + ranking rules.
  const eligible = meals.filter((m) => baseEligible(m, maxPrepMinutes));
  const inBand = rank(
    eligible
      .filter((m) => Math.abs(m.totals.calories - gap) <= gap * CATCH_UP_BAND)
      .map((m) => candidate(m, ["bridge"], maxPrepMinutes)),
  );
  const pick = inBand[0] ?? rank(eligible.map((m) => candidate(m, [], maxPrepMinutes)))[0];
  const suggestion = pick
    ? ` — ${pick.meal.name} fixes it in ${pick.meal.prep_minutes} min`
    : "";
  return {
    fireAtMinutes: fireAt,
    title: "Eat something",
    body: `~${gap} cal to go${suggestion}`,
  };
}
